name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and test (iOS 13.0)
      run: xcodebuild test -scheme SFUserFriendlySymbols -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 8'
    - name: Build and test (iOS 14.0.1)
      run: xcodebuild test -scheme SFUserFriendlySymbols -destination 'platform=iOS Simulator,OS=14.0.1,name=iPhone 8'
    - name: Build and test (iOS 14.2)
      run: xcodebuild test -scheme SFUserFriendlySymbols -destination 'platform=iOS Simulator,OS=14.2,name=iPhone 8'
    - name: Build and test (iOS 14.5)
      run: xcodebuild test -scheme SFUserFriendlySymbols -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 8'
    - name: Build and test (iOS 15.0)
      run: xcodebuild test -scheme SFUserFriendlySymbols -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 8'
    - name: Build and test (iOS 15.2)
      run: xcodebuild test -scheme SFUserFriendlySymbols -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 8'
